/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 room-1-4.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room-1-4.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Clock.geometry} material={nodes.Clock.material} position={[-3.966, 3.98, -1.421]} rotation={[0, -0.77, 0]} scale={1.224}>
        <mesh geometry={nodes.hours.geometry} material={nodes.hours.material} />
        <mesh geometry={nodes.minutes.geometry} material={nodes.minutes.material} />
        <mesh geometry={nodes.secondes.geometry} material={nodes.secondes.material} />
      </mesh>
      <mesh geometry={nodes.Plane040.geometry} material={nodes.Plane040.material} position={[-0.588, 1.834, 2.989]} scale={1.201} />
      <mesh geometry={nodes.schrodinger.geometry} material={nodes.schrodinger.material} position={[-0.299, 1.898, 2.997]} rotation={[0, -0.469, 0]} />
      <mesh geometry={nodes['coffe-smoke'].geometry} material={nodes['coffe-smoke'].material} position={[-0.312, 1.972, 2.997]} rotation={[0, -0.486, 0]} />
      <mesh geometry={nodes['photo-7'].geometry} material={nodes['photo-7'].material} position={[-2.14, 3.333, -3.241]} />
      <mesh geometry={nodes['photo-6'].geometry} material={nodes['photo-6'].material} position={[-1.709, 3.488, -3.676]} />
      <mesh geometry={nodes['photo-1'].geometry} material={nodes['photo-1'].material} position={[-2.54, 4.163, -2.825]} />
      <mesh geometry={nodes['photo-8'].geometry} material={nodes['photo-8'].material} position={[-2.501, 3.578, -2.871]} />
      <mesh geometry={nodes['photo-4'].geometry} material={nodes['photo-4'].material} position={[-1.619, 4.157, -3.767]} />
      <mesh geometry={nodes['photo-5'].geometry} material={nodes['photo-5'].material} position={[-1.306, 3.661, -4.094]} />
      <mesh geometry={nodes['photo-2'].geometry} material={nodes['photo-2'].material} position={[-2.092, 3.854, -3.287]} />
      <mesh geometry={nodes['photo-3'].geometry} material={nodes['photo-3'].material} position={[-2.095, 4.372, -3.29]} />
    </group>
  )
}

useGLTF.preload('/room-1-4.glb')
