/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Room-3-3.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Room-3-3.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[1.627, 1.825, 1.218]} rotation={[0, 0.829, 0]} scale={1.674}>
        <mesh geometry={nodes.Mouse_final.geometry} material={nodes.Mouse_final.material} />
        <mesh geometry={nodes.wheel.geometry} material={nodes.wheel.material} />
      </group>
      <group position={[0.291, 1.82, 2.247]} rotation={[0, 1.13, 0]} scale={[2.26, 2.033, 2.26]}>
        <mesh geometry={nodes['laptop-screen'].geometry} material={nodes['laptop-screen'].material} />
        <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} />
      </group>
      <group position={[-0.757, 0.401, 2.614]} rotation={[0, -0.926, 0]} scale={1.899}>
        <mesh geometry={nodes['case'].geometry} material={nodes['case'].material} />
        <mesh geometry={nodes.case001.geometry} material={nodes.case001.material} />
        <mesh geometry={nodes.caseinside.geometry} material={nodes.caseinside.material} />
        <mesh geometry={nodes.fan.geometry} material={nodes.fan.material} />
        <mesh geometry={nodes.fan001.geometry} material={nodes.fan001.material} />
        <mesh geometry={nodes.fan002.geometry} material={nodes.fan002.material} />
        <mesh geometry={nodes.fan003.geometry} material={nodes.fan003.material} />
        <mesh geometry={nodes.fan004.geometry} material={nodes.fan004.material} />
        <mesh geometry={nodes.Plane004.geometry} material={nodes.Plane004.material} />
      </group>
      <group position={[1.484, 0.407, 2.386]} rotation={[Math.PI, -1.24, Math.PI]} scale={1.899}>
        <mesh geometry={nodes.Arm_Rests.geometry} material={nodes.Arm_Rests.material} />
        <mesh geometry={nodes.Crossbar.geometry} material={nodes.Crossbar.material} />
        <mesh geometry={nodes['Cushion_-Bottom'].geometry} material={nodes['Cushion_-Bottom'].material} />
        <mesh geometry={nodes['Cushions_-_Back'].geometry} material={nodes['Cushions_-_Back'].material} />
        <mesh geometry={nodes.Frame.geometry} material={nodes.Frame.material} />
        <mesh geometry={nodes.Gas_Strut.geometry} material={nodes.Gas_Strut.material} />
        <mesh geometry={nodes['Legs&_Wheels#'].geometry} material={nodes['Legs&_Wheels#'].material} />
        <mesh geometry={nodes['Legs&_Wheels#001'].geometry} material={nodes['Legs&_Wheels#001'].material} />
        <mesh geometry={nodes['Legs&_Wheels#002'].geometry} material={nodes['Legs&_Wheels#002'].material} />
        <mesh geometry={nodes['Legs&_Wheels#003'].geometry} material={nodes['Legs&_Wheels#003'].material} />
        <mesh geometry={nodes['Legs&_Wheels#004'].geometry} material={nodes['Legs&_Wheels#004'].material} />
        <mesh geometry={nodes['Supprt_-_V'].geometry} material={nodes['Supprt_-_V'].material} />
        <mesh geometry={nodes.T_Joint.geometry} material={nodes.T_Joint.material} />
      </group>
      <group position={[1.023, 1.818, 1.002]} rotation={[0, 0.325, 0]} scale={2.052}>
        <mesh geometry={nodes.Monitor.geometry} material={nodes.Monitor.material} />
        <mesh geometry={nodes['pc-screen'].geometry} material={nodes['pc-screen'].material} />
      </group>
      <mesh geometry={nodes.Modern_Desk.geometry} material={nodes.Modern_Desk.material} position={[0.695, 0.068, -0.039]} rotation={[0, -0.78, 0]} scale={1.628} />
      <mesh geometry={nodes.Desk_Lamp.geometry} material={nodes.Desk_Lamp.material} position={[-0.824, 2.35, 2.796]} rotation={[0, -1.135, 0]} scale={1.946} />
      <mesh geometry={nodes.Circle_Rug.geometry} material={nodes.Circle_Rug.material} position={[0.695, 0.068, -0.039]} rotation={[0, -0.78, 0]} scale={1.628} />
      <mesh geometry={nodes.Blender_keyboard.geometry} material={nodes.Blender_keyboard.material} position={[0.674, 0.068, 0.054]} rotation={[0, -0.78, 0]} scale={1.628} />
      <mesh geometry={nodes.Black_circle_round_carpet.geometry} material={nodes.Black_circle_round_carpet.material} position={[0.695, 0.043, -0.039]} rotation={[0, -0.78, 0]} scale={1.628} />
    </group>
  )
}

useGLTF.preload('/Room-3-3.glb')
