/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 suzanne.glb
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { HolographicMaterial } from './HolographicMaterial'

const Model = (props) => {
  const { nodes } = useGLTF('/models/suzanne.glb')
  const ref = useRef()

  // useFrame(({ clock }) => {
  //   const t = clock.getElapsedTime()
  //   if (ref.current) {
  //     ref.current.rotation.x = -t * 0.1
  //     ref.current.rotation.y = t * 0.2
  //   }
  // })

  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh
        geometry={nodes.Suzanne.geometry}
        position={[0.667, 1.688, -1.985]}
        scale={0.232}
      >
        <HolographicMaterial />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/suzanne.glb')

export default Model