/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Converted & optimized for interactive baked hit-box workflow
*/

"use client";

import { useGLTF } from "@react-three/drei";
import gsap from "gsap";
import React, { useRef, useMemo, useState, useEffect } from "react";
import { Mesh, MeshBasicMaterial, MeshStandardMaterial } from "three";

import useInteractionStore from "@/store/useInteractionStore";

type GLTFResult = {
  nodes: Record<string, Mesh>;
};

const HitBoxes_Baked: React.FC<React.ComponentProps<"group">> = (props) => {
  const { nodes } = useGLTF("/models/hit-boxes.glb") as unknown as GLTFResult;
  const { clickedObject } = useInteractionStore();

  // 🟦 Transparent hit-box material
  const hitBoxMaterial = useMemo(
    () =>
      new MeshBasicMaterial({
        transparent: true,
        opacity: 0,
        depthWrite: false,
      }),
    []
  );

  // 💠 Glowing corners material
  const cornersMaterial = useMemo(
    () =>
      new MeshStandardMaterial({
        color: "#5394fc",
        emissive: "#5394fc",
        emissiveIntensity: 1.5,
      }),
    []
  );

  // 🧩 Refs for corner meshes
  const refs = {
    Clock: useRef<Mesh>(null),
    Library: useRef<Mesh>(null),
    Mug: useRef<Mesh>(null),
    Photos: useRef<Mesh>(null),
  };

  // 🧠 Hover states
  const [hovered, setHovered] = useState({
    Clock: false,
    Library: false,
    Mug: false,
    Photos: false,
  });

  // 🎞 Animate corner visibility when hovered or clicked
  useEffect(() => {
    Object.entries(refs).forEach(([key, ref]) => {
      gsap.to(ref.current?.scale || {}, {
        x:
          hovered[key as keyof typeof hovered] || clickedObject === key ? 1 : 0,
        y:
          hovered[key as keyof typeof hovered] || clickedObject === key ? 1 : 0,
        z:
          hovered[key as keyof typeof hovered] || clickedObject === key ? 1 : 0,
        duration: 0.4,
        ease: "power2.out",
      });
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [hovered, clickedObject]);

  // 🧩 Object definitions for hit-boxes
  const objects = [
    {
      name: "Clock",
      corner: "corners-clock",
      box: "hit-box-clock",
      positionCorner: [-3.698, 3.968, -1.555],
      positionBox: [-3.733, 3.968, -1.59],
    },
    {
      name: "Library",
      corner: "corners-library",
      box: "hit-box-library",
      positionCorner: [3.556, 3.369, -0.445],
      positionBox: [3.876, 3.369, -0.775],
    },
    {
      name: "Mug",
      corner: "corners-mug",
      box: "hit-box-mug",
      positionCorner: [-0.328, 1.949, 2.99],
      positionBox: [-0.328, 1.949, 2.99],
    },
    {
      name: "Photos",
      corner: "corners-photos",
      box: "hit-box-photos",
      positionCorner: [-1.583, 3.824, -3.638],
      positionBox: [-1.62, 3.824, -3.675],
    },
  ];

  return (
    <group {...props} dispose={null}>
      {objects.map((obj) => (
        <group key={obj.name}>
          {/* 💠 Corners (glowing, animated) */}
          <mesh
            ref={refs[obj.name as keyof typeof refs]}
            geometry={nodes[obj.corner].geometry}
            material={cornersMaterial}
            position={obj.positionCorner as [number, number, number]}
            scale={0}
          />

          {/* 🟦 Hit-box (invisible but interactive) */}
          <mesh
            name={obj.name}
            geometry={nodes[obj.box].geometry}
            material={hitBoxMaterial}
            position={obj.positionBox as [number, number, number]}
            onPointerOver={() => {
              setHovered((prev) => ({ ...prev, [obj.name]: true }));
              document.body.style.cursor = "pointer";
            }}
            onPointerOut={() => {
              setHovered((prev) => ({ ...prev, [obj.name]: false }));
              document.body.style.cursor = "auto";
            }}
          />
        </group>
      ))}
    </group>
  );
};

useGLTF.preload("/models/hit-boxes.glb");

export default HitBoxes_Baked;
